class EventType:
    CONN_CONNECTED = "CONN_CONNECTED"
    CONN_STAT = "CONN_STAT"
    CONN_CLOSED = "CONN_CLOSED"

    MARKET_ORDER_BOOK = "MARKET_ORDER_BOOK"
    MARKET_PRICE = "MARKET_PRICE"
    MARKET_TRADE = "MARKET_TRADE"
    MARKET_BAR = "MARKET_BAR"

    EXCHANGE_EXECUTION = "EXCHANGE_EXECUTION"
    EXCHANGE_ORDER = "EXCHANGE_ORDER"

    ORDER_CREATED = "ORDER_CREATED"
    ORDER_UPDATED = "ORDER_UPDATED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_ERROR = "ORDER_ERROR"

    TRADING_PNL_UPDATE = "TRADING_PNL_UPDATE"
    TRADING_STOP = "TRADING_STOP"

    MSG_OUT = "MSG_OUT"
    MSG_IN = "MSG_IN"
    METRICS = "METRICS"
    EXCEPTION = "EXCEPTION"
    EV_LOOP_EXIT = "EV_LOOP_EXIT"
